// Human integration step (no build tooling on the page): bundle the curated eras.json and
// K3's per-era scene SVGs into two plain <script> globals the static site loads directly.
//   data/eras.js   -> window.ERAS, window.META
//   data/scenes.js -> window.SCENES  ({ eraId: "<inner svg markup>" })
// Run after (re)generating scenes:  node tools/build-data.mjs

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const data = JSON.parse(readFileSync(join(ROOT, "data", "eras.json"), "utf8"));
const eras = data.eras;

const meta = {
  place: data.place,
  vantage: data.vantage,
  metricsNote: data.metricsNote,
  confidenceLevels: data.confidenceLevels,
};

writeFileSync(
  join(ROOT, "data", "eras.js"),
  "/* Generated by tools/build-data.mjs from data/eras.json — do not edit by hand. */\n" +
    "window.ERAS = " + JSON.stringify(eras) + ";\n" +
    "window.META = " + JSON.stringify(meta) + ";\n"
);

// K3 sometimes emits bare "&" inside attribute values it copied verbatim from the data
// (e.g. data-hotspot="Bohío village & batey"). Browsers tolerate it, but escape stray
// ampersands to valid entities so the SVG is clean XML too.
function escapeBareAmp(svg) {
  return svg.replace(/&(?!(amp|lt|gt|quot|apos|#\d+|#x[0-9a-fA-F]+);)/g, "&amp;");
}

const scenes = {};
let missing = [];
for (const era of eras) {
  const p = join(ROOT, "scenes", `${era.id}.svg`);
  if (existsSync(p)) scenes[era.id] = escapeBareAmp(readFileSync(p, "utf8").trim());
  else missing.push(era.id);
}
writeFileSync(
  join(ROOT, "data", "scenes.js"),
  "/* Generated by tools/build-data.mjs from scenes/*.svg (authored by Kimi K3). */\n" +
    "window.SCENES = " + JSON.stringify(scenes) + ";\n"
);

console.log(
  `Wrote data/eras.js (${eras.length} eras) and data/scenes.js (${Object.keys(scenes).length} scenes).`
);
if (missing.length) console.warn("Missing scenes for: " + missing.join(", "));
